apiVersion: v1
kind: Service
metadata:
  name: web-app-cars-service
spec:
  selector:
    app: web-app-cars-app
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-cars-app
spec:
  selector:
    matchLabels:
      app: web-app-cars-app
  replicas: 5
  template:
    metadata:
      labels:
        app: web-app-cars-app
    spec:
      containers:
        - name: web-app-cars-container
          image: ankitmishraedu/web_app_car_backend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
